spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    host: ${ALDRA_DB_HOST:127.0.0.1}
    port: ${ALDRA_DB_PORT:15432}
    db-name: ${ALDRA_DB_NAME:aldra_db}
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.db-name}
    username: ${ALDRA_DB_USER:aldra}
    password: ${ALDRA_DB_PASSWORD:aldra}
