spring:
  profiles:
    active: local
  config:
    import:
      - classpath:application-database.yml

app:
  batch:
    execute: ${EXECUTION_JOB:Sample}

logging:
  level:
    root: warn
    com.s_kugel.aldra.batch: info
